// Shared materials of 桜都駅 (cached by ctx.mat, so identical calls share one material and batch together).
export function makeMaterials(ctx, tx) {
  const { mat } = ctx;
  return {
    floor: mat.toon('#ffffff', { map: tx.floor, paint: 0.03 }),
    plat: mat.toon('#ffffff', { map: tx.platform, paint: 0.04 }),
    dot: mat.toon('#ffffff', { map: tx.tactile.dot, paint: 0.02, polygonOffset: -1 }),
    line: mat.toon('#ffffff', { map: tx.tactile.line, paint: 0.02, polygonOffset: -1 }),
    ceiling: mat.toon('#ffffff', { map: tx.ceiling, paint: 0.02 }),
    wall: mat.toon('#ffffff', { map: tx.wall, paint: 0.03 }),
    concrete: mat.toon('#ffffff', { map: tx.concrete, paint: 0.05 }),
    concreteD: mat.toon('#9f9d97', { paint: 0.05 }),
    ballast: mat.toon('#ffffff', { map: tx.ballast, paint: 0.04 }),
    light: mat.emissive('#f2f6ff', 1.12),
    warm: mat.emissive('#ffe3b8', 0.9),
    pillar: mat.toon('#e6e3dc', { paint: 0.03 }),
    band: mat.toon('#0a5fb0', { paint: 0.02 }),
    bandS: mat.toon('#1a4f96', { paint: 0.02 }),
    steel: mat.toon('#a4abb2', { paint: 0.03 }),
    steelD: mat.toon('#5d636b', { paint: 0.03 }),
    white: mat.toon('#eeede8', { paint: 0.02 }),
    edge: mat.toon('#eeece6', { paint: 0.02, polygonOffset: -1 }),
    black: mat.toon('#3a3346', { paint: 0.01 }),
    rail: mat.toon('#8d8680', { paint: 0.03 }),
    railTop: mat.toon('#d9dde2', { paint: 0.01 }),
    sleeper: mat.toon('#a19f99', { paint: 0.04 }),
    slab: mat.toon('#bab8b1', { paint: 0.04 }),
    glass: mat.glass({ tint: '#9fb6c8', opacity: 0.22 }),
    glassDark: mat.glass({ tint: '#6f8699', opacity: 0.45 }),
    tread: mat.toon('#cfcac0', { paint: 0.03 }),
    nosing: mat.toon('#4b4d52', { paint: 0.02 }),
    escBody: mat.toon('#c7ccd2', { paint: 0.02 }),
    escStep: mat.toon('#6d747c', { paint: 0.02 }),
    handrail: mat.toon('#2d3038', { paint: 0.01 }),
    yellow: mat.toon('#e8bf2c', { paint: 0.02 }),
    red: mat.toon('#d9463b', { paint: 0.02 }),
    wood: mat.toon('#b48a62', { paint: 0.05 }),
  };
}
